# Generated by Django 5.0.6 on 2024-05-17 19:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('cover', models.ImageField(upload_to='book_covers/', verbose_name='Фото книги')),
                ('categories', models.ManyToManyField(related_name='books', to='website.category', verbose_name='Категории')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тема')),
                ('books', models.ManyToManyField(related_name='topics', to='website.book', verbose_name='Книги')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images/', verbose_name='Изображение')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='website.topic', verbose_name='Тема')),
            ],
        ),
    ]
