# Generated by Django 5.0.6 on 2024-05-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_article_image_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
