# Generated by Django 5.0.6 on 2024-05-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
    ]
